services:

  frontend:
    build: ./frontend
    container_name: frontend_web
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"
    depends_on:
      - api

  api:
    build: ./api
    container_name: backend_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio_storage
    command: server /data --console-address ":9003"
    ports:
      - "9002:9000"
      - "9003:9003"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:

